#   Project
### **Name :** *Raahima Rashid Peracha*
### **Class:** *BS Data Science (3A)*
### **Roll No.:** *SU92-BSDSM-F24-041*
### **Subject :** *Artificial Intelligence (Lab)*
### **Instructor:** *Sir Rasikh Ali*

Data set Link : https://www.kaggle.com/datasets/uciml/german-credit

<div style="background-color: #cff4fc; color: #0369a1; padding: 15px; border-radius: 8px;">
<strong>Data Acquisition</strong>
</div>

In [ ]:
import pandas as pd
import numpy as np
import joblib
import pickle

from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [87]:
df = pd.read_csv('german_credit_data.csv')

In [88]:
df.head()

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,0,67,male,2,own,NaN,little,1169,6,radio/TV,good
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,bad
2,2,49,male,1,own,little,NaN,2096,12,education,good
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,good
4,4,53,male,2,free,little,little,4870,24,car,bad

In [89]:
df.tail()

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
995,995,31,female,1,own,little,NaN,1736,12,furniture/equipment,good
996,996,40,male,3,own,little,little,3857,30,car,good
997,997,38,male,2,own,little,NaN,804,12,radio/TV,good
998,998,23,male,2,free,little,little,1845,45,radio/TV,bad
999,999,27,male,2,own,moderate,moderate,4576,45,car,good

In [90]:
print('rows: ', df.shape[0])
print('columns: ', df.shape[1])

rows:  1000
columns:  11

In [91]:
for i in df.columns:
    print(i)

Unnamed: 0
Age
Sex
Job
Housing
Saving accounts
Checking account
Credit amount
Duration
Purpose
Risk

In [92]:
df.count()

Unnamed: 0          1000
Age                 1000
Sex                 1000
Job                 1000
Housing             1000
Saving accounts      817
Checking account     606
Credit amount       1000
Duration            1000
Purpose             1000
Risk                1000
dtype: int64

In [93]:
df['Purpose'].unique()

array(['radio/TV', 'education', 'furniture/equipment', 'car', 'business',
       'domestic appliances', 'repairs', 'vacation/others'], dtype=object)

In [94]:
df.dtypes

Unnamed: 0           int64
Age                  int64
Sex                 object
Job                  int64
Housing             object
Saving accounts     object
Checking account    object
Credit amount        int64
Duration             int64
Purpose             object
Risk                object
dtype: object

In [95]:
df.nunique()

Unnamed: 0          1000
Age                   53
Sex                    2
Job                    4
Housing                3
Saving accounts        4
Checking account       3
Credit amount        921
Duration              33
Purpose                8
Risk                   2
dtype: int64

In [96]:
df.describe()

        Unnamed: 0          Age          Job  Credit amount     Duration
count  1000.000000  1000.000000  1000.000000    1000.000000  1000.000000
mean    499.500000    35.546000     1.904000    3271.258000    20.903000
std     288.819436    11.375469     0.653614    2822.736876    12.058814
min       0.000000    19.000000     0.000000     250.000000     4.000000
25%     249.750000    27.000000     2.000000    1365.500000    12.000000
50%     499.500000    33.000000     2.000000    2319.500000    18.000000
75%     749.250000    42.000000     2.000000    3972.250000    24.000000
max     999.000000    75.000000     3.000000   18424.000000    72.000000

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1000 non-null   int64
 1   Age               1000 non-null   int64
 2   Sex               1000 non-null   object
 3   Job               1000 non-null   int64
 4   Housing           1000 non-null   object
 5   Saving accounts   817 non-null    object
 6   Checking account  606 non-null    object
 7   Credit amount     1000 non-null   int64
 8   Duration          1000 non-null   int64
 9   Purpose           1000 non-null   object
 10  Risk              1000 non-null   object
dtypes: int64(5), object(6)
memory usage: 86.1+ KB

In [98]:
df.isnull().sum()

Unnamed: 0            0
Age                   0
Sex                   0
Job                   0
Housing               0
Saving accounts     183
Checking account    394
Credit amount         0
Duration              0
Purpose               0
Risk                  0
dtype: int64

<div style="background-color: #ede9fe; color: #6d28d9; padding: 15px; border-radius: 8px;">
 <strong>Exploratory Data Analysis (EDA)</strong>
</div>

In [99]:
df['Saving accounts'] = df['Saving accounts'].fillna('unknown')
df['Checking account'] = df['Checking account'].fillna('unknown')

In [ ]:
# I have taken this code from Claude AI as i don't know how to covert DM to PKR in coding
DM_TO_PKR = 31
df['Credit amount'] = df['Credit amount'] * DM_TO_PKR
print("Credit amount converted from DM to PKR ✅")
print(df['Credit amount'].describe())

Credit amount converted from DM to PKR ✅
count      1000.000000
mean     101408.998000
std       87504.843155
min        7750.000000
25%       42330.500000
50%       71904.500000
75%      123139.750000
max      571144.000000
Name: Credit amount, dtype: float64

In [101]:
df.isnull().sum()

Unnamed: 0          0
Age                 0
Sex                 0
Job                 0
Housing             0
Saving accounts     0
Checking account    0
Credit amount       0
Duration            0
Purpose             0
Risk                0
dtype: int64

In [102]:
df.rename(columns={'Unnamed: 0': 'id'}, inplace=True)

In [103]:
df.columns

Index(['id', 'Age', 'Sex', 'Job', 'Housing', 'Saving accounts',
       'Checking account', 'Credit amount', 'Duration', 'Purpose', 'Risk'],
      dtype='object')

In [104]:
encoders = {}
columns_to_encode = ['Sex', 'Housing', 'Saving accounts', 'Checking account', 'Purpose']

def encodeCols(cols):
    for i in cols:
        value = pd.DataFrame({i:df[i].unique()})
        LE = LabelEncoder()
        LE.fit(value)
        df[i] = LE.transform(df[i])
        encoders[i] = LE

columns = ['Sex', 'Job', 'Housing', 'Saving accounts', 'Checking account', 'Purpose']
encodeCols(columns)

# Save encoders
joblib.dump(encoders, "encoders.pkl")

c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

['encoders.pkl']

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                1000 non-null   int64
 1   Age               1000 non-null   int64
 2   Sex               1000 non-null   int32
 3   Job               1000 non-null   int64
 4   Housing           1000 non-null   int32
 5   Saving accounts   1000 non-null   int32
 6   Checking account  1000 non-null   int32
 7   Credit amount     1000 non-null   int64
 8   Duration          1000 non-null   int64
 9   Purpose           1000 non-null   int32
 10  Risk              1000 non-null   object
dtypes: int32(5), int64(5), object(1)
memory usage: 66.5+ KB

In [106]:
df.to_csv('cleaned_data.csv', index=False, header=True)

<div style="background-color: #ffedd5; color: #c2410c; padding: 15px; border-radius: 8px;">
<strong>Train-Test Splitting</strong>
</div>

In [107]:
df=pd.read_csv('cleaned_data.csv')

In [108]:
df.head()

,id,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,0,67,1,2,1,4,0,36239,6,5,good
1,1,22,0,2,1,0,1,184481,48,5,bad
2,2,49,1,1,1,0,3,64976,12,3,good
3,3,45,1,2,0,0,0,244342,42,4,good
4,4,53,1,2,0,0,0,150970,24,1,bad

In [109]:
df.columns

Index(['id', 'Age', 'Sex', 'Job', 'Housing', 'Saving accounts',
       'Checking account', 'Credit amount', 'Duration', 'Purpose', 'Risk'],
      dtype='object')

In [110]:
X = df.drop(['Risk', 'id'], axis=1) 
y = df['Risk']

In [ ]:
y = y.map({'good': 0, 'bad': 1})

In [112]:
X.head()

,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose
0,67,1,2,1,4,0,36239,6,5
1,22,0,2,1,0,1,184481,48,5
2,49,1,1,1,0,3,64976,12,3
3,45,1,2,0,0,0,244342,42,4
4,53,1,2,0,0,0,150970,24,1

In [113]:
y.head()

0    0
1    1
2    0
3    0
4    1
Name: Risk, dtype: int64

In [114]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2, random_state=100)

In [115]:
train_X.head()
train_y.head()

675    0
358    0
159    0
533    0
678    0
Name: Risk, dtype: int64

In [116]:
test_X.head()
test_y.head()

249    1
353    1
537    0
424    1
564    0
Name: Risk, dtype: int64

In [117]:
print(train_X.shape, train_y.shape)
print(test_X.shape, test_y.shape)

(800, 9) (800,)
(200, 9) (200,)

<div style="background-color: #dcfce7; color: #15803d; padding: 15px; border-radius: 8px;">
<strong>Model Training and Accuracy</strong>
</div>

In [118]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\dell\anaconda3\lib\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\users\dell\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\dell\anaconda3\lib\site-packages (from xgboost) (1.13.1)

In [119]:
from xgboost import XGBClassifier
# Initializing the model with professional parameters
model = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=5, random_state=100)

In [ ]:
model.fit(train_X, train_y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
import joblib

joblib.dump(model,open ('credit_risk_model.pkl','wb'))

In [122]:
model = joblib.load(open('credit_risk_model.pkl', 'rb'))

<div style="background-color: #dcfce7; color: #15803d; padding: 15px; border-radius: 8px;">
<strong>Model Training and Accuracy</strong>
</div>

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(test_X)

In [126]:
accuracy = accuracy_score(test_y, y_pred)
print(f"Final Model Accuracy: {accuracy * 100:.2f}%")

print("Classification Report:", end='')
print(classification_report(test_y, y_pred))

Final Model Accuracy: 72.50%
Classification Report:              precision    recall  f1-score   support

           0       0.80      0.83      0.81       144
           1       0.51      0.46      0.49        56

    accuracy                           0.72       200
   macro avg       0.65      0.65      0.65       200
weighted avg       0.72      0.72      0.72       200

<div style="background-color: #b4e9c7; color: #157980; padding: 15px; border-radius: 8px;">
<strong>Application Phase</strong>
</div>

In [125]:
import numpy as np

def encode_cols(le, value):
    if value in le.classes_:
        return le.transform([value])[0]
    else:
        return le.transform([le.classes_[0]])[0]

print("Enter applicant details to predict credit risk:")
applicant_data = {
    'Age': int(input("Age: ")),
    'Sex': input("Sex (male/female): ").lower(),
    'Job': int(input("Job (0-3): ")),  
    'Housing': input("Housing (own/rent/free): ").lower(),
    'Saving accounts': input("Saving accounts (little/moderate/rich/quite rich/unknown): ").lower(),
    'Checking account': input("Checking account (little/moderate/rich/quite rich/unknown): ").lower(),
    'Credit amount': int(input("Credit amount: ")),
    'Duration': int(input("Duration (months): ")),
    'Purpose': input("Purpose (car/education/furniture/electronics/repairs/other): ").lower()
}

# Encode categorical features
for col in ['Sex', 'Job', 'Housing', 'Saving accounts', 'Checking account', 'Purpose']:
    le = encoders[col]
    applicant_data[col] = encode_cols(le, applicant_data[col])

features = [
    'Age', 'Sex', 'Job', 'Housing', 'Saving accounts', 
    'Checking account', 'Credit amount', 'Duration', 'Purpose'
]

X = np.array([[applicant_data[col] for col in features]])

predict = model.predict(X)
print("Predicted Credit Risk:", "Bad" if predict[0] == 1 else "Good")

Enter applicant details to predict credit risk:
Predicted Credit Risk: Good